site_name: Valentin Lewicki
site_url: https://vlewicki.github.io
site_author: Valentin Lewicki
site_description: Notes About Programming and Life
theme:
  font:
    text: noto serif
    code: noto mono
  favicon: assets/favicon.svg
  name: material
  logo: assets/logo.svg
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  plugins:
    - search
    - social:
      cards_layout: default/variant
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - search.suggest
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      # accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
    anchor_linenums: true
  - pymdownx.superfences:
